doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'
        charset: utf8
        
        # PostgreSQL specific configuration
        driver: 'pdo_pgsql'
        
        # Use JSONB for better performance with JSON data
        types:
            json: Doctrine\DBAL\Types\JsonType
            jsonb: App\Domain\Type\JsonbType
            uuid: App\Domain\Type\UuidType
            email: App\Infrastructure\Doctrine\Type\EmailType
            phone: App\Infrastructure\Doctrine\Type\PhoneType
            money: App\Infrastructure\Doctrine\Type\MoneyType
            slug: App\Infrastructure\Doctrine\Type\SlugType
            address: App\Infrastructure\Doctrine\Type\AddressType
            order_number: App\Infrastructure\Doctrine\Type\OrderNumberType
            product_sku: App\Infrastructure\Doctrine\Type\ProductSkuType
            
        # Enable query logging in development
        logging: '%kernel.debug%'
        profiling_collect_backtrace: '%kernel.debug%'

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App
            AppValueObject:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/ValueObject'
                prefix: 'App\Domain\ValueObject'
                alias: AppValueObject

        # Performance configuration (intentionally basic for Phase 1)
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
