nelmio_api_doc:
    documentation:
        info:
            title: Symfony Headless E-commerce API
            description: A modern headless e-commerce platform demonstrating performance optimization journey
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/auth/login:
                post:
                    tags: ['Authentication']
                    summary: 'Authenticate using email and password'
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: '#App/Infrastructure/OpenApi/Schema/LoginRequest'
                    responses:
                        '200':
                            description: 'Authentication succeeded.'
                            content:
                                application/json:
                                    schema:
                                        $ref: '#App/Infrastructure/OpenApi/Schema/LoginResponse'
                        '401':
                            description: 'Invalid credentials or inactive account.'
                            content:
                                application/json:
                                    schema:
                                        $ref: '#App/Infrastructure/OpenApi/Schema/ErrorResponse'